// Curated & verified now-playing movies data for CineMeow
export const NOW_PLAYING_MOVIES = [
    {
        id: "dune-2",
        title: "Dune: Hành Tinh Cát - Phần Hai",
        originalTitle: "Dune: Part Two",
        genres: "Khoa học viễn tưởng, Phiêu lưu, Kịch tính",
        rating: "T16",
        score: 9.3,
        voteCount: "34.5K",
        duration: "166 phút",
        releaseDate: "01/03/2026",
        formats: ["IMAX 2D", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
        trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w",
        isHot: true,
        isEarlyScreening: false,
        synopsis: "Paul Atreides hợp lực cùng Chani và tộc người Fremen để trả thù những kẻ đã hủy hoại gia tộc mình, đối mặt với sự lựa chọn định đoạt tương lai của vũ trụ.",
    },
    {
        id: "deadpool-wolverine",
        title: "Deadpool & Wolverine",
        originalTitle: "Deadpool & Wolverine",
        genres: "Hành động, Hài hước, Viễn tưởng",
        rating: "T18",
        score: 9.1,
        voteCount: "48.2K",
        duration: "128 phút",
        releaseDate: "26/07/2026",
        formats: ["2D Phụ đề", "3D", "IMAX 2D"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        trailerUrl: "https://www.youtube.com/embed/73_1biulkYk",
        isHot: true,
        isEarlyScreening: false,
        synopsis: "Cặp bài trùng lầy lội tái xuất khi Cơ quan Quản lý Phương sai Thời gian lôi kéo Wade Wilson vào một sứ mệnh giải cứu đa vũ trụ cùng Wolverine.",
    },
    {
        id: "fantastic-four",
        title: "Bộ Tứ Siêu Đẳng: First Steps",
        originalTitle: "The Fantastic Four: First Steps",
        genres: "Khoa học viễn tưởng, Hành động, Phiêu lưu",
        rating: "T13",
        score: 8.8,
        voteCount: "19.8K",
        duration: "135 phút",
        releaseDate: "25/07/2026",
        formats: ["IMAX 2D", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
        trailerUrl: "https://www.youtube.com/embed/18QQWa3Wcx0",
        isHot: true,
        isEarlyScreening: true,
        synopsis: "Gia đình siêu anh hùng đầu tiên của Marvel bước vào vũ trụ điện ảnh trong bối cảnh retro-future thập niên 60 chống lại hiểm họa Galactus.",
    },
    {
        id: "inside-out-2",
        title: "Inside Out 2: Cảm Xúc Mới",
        originalTitle: "Inside Out 2",
        genres: "Hoạt hình, Hài hước, Gia đình",
        rating: "P",
        score: 9.0,
        voteCount: "55.4K",
        duration: "96 phút",
        releaseDate: "14/06/2026",
        formats: ["2D Lồng tiếng", "2D Phụ đề", "3D"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        trailerUrl: "https://www.youtube.com/embed/LEjhY15eCx0",
        isHot: true,
        isEarlyScreening: false,
        synopsis: "Riley bước vào tuổi dậy thì, trụ sở cảm xúc chào đón những người bạn mới: Lo Âu, Ghen Tị, Xấu Hổ và Chán Nản làm đảo lộn mọi thứ.",
    },
    {
        id: "despicable-me-4",
        title: "Kẻ Trộm Mặt Trăng 4",
        originalTitle: "Despicable Me 4",
        genres: "Hoạt hình, Hài hước, Gia đình",
        rating: "P",
        score: 8.5,
        voteCount: "31.2K",
        duration: "95 phút",
        releaseDate: "05/07/2026",
        formats: ["2D Lồng tiếng", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
        trailerUrl: "https://www.youtube.com/embed/qQlr9-gF32Q",
        isHot: false,
        isEarlyScreening: false,
        synopsis: "Gru và đại gia đình Minions đối đầu với kẻ thù không đội trời chung Maxime Le Mal, buộc cả gia đình phải cải trang chuyển chỗ ở.",
    },
    {
        id: "spiderman-spiderverse",
        title: "Người Nhện: Du Hành Vũ Trụ Nhện",
        originalTitle: "Spider-Man: Across the Spider-Verse",
        genres: "Hoạt hình, Hành động, Viễn tưởng",
        rating: "T13",
        score: 9.2,
        voteCount: "66.7K",
        duration: "140 phút",
        releaseDate: "02/06/2026",
        formats: ["IMAX 2D", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        trailerUrl: "https://www.youtube.com/embed/cqGjhVJWtEg",
        isHot: true,
        isEarlyScreening: false,
        synopsis: "Miles Morales bị cuốn qua đa vũ trụ, nơi cậu phải đối đầu với toàn bộ Quân đoàn Nhện để bảo vệ định mệnh của những người cậu yêu thương.",
    },
    {
        id: "kungfu-panda-4",
        title: "Kung Fu Panda 4",
        originalTitle: "Kung Fu Panda 4",
        genres: "Hoạt hình, Phiêu lưu, Hành động",
        rating: "P",
        score: 8.7,
        voteCount: "25.1K",
        duration: "94 phút",
        releaseDate: "08/03/2026",
        formats: ["2D Lồng tiếng", "2D Phụ đề", "3D"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
        trailerUrl: "https://www.youtube.com/embed/_inKs4eeHiI",
        isHot: false,
        isEarlyScreening: false,
        synopsis: "Po được chọn làm Thủ lĩnh Tinh thần của Thung lũng Hòa Bình và phải tìm kiếm một Chiến binh Rồng mới, đồng thời đối đầu với Tắc Kè Bông xảo quyệt.",
    },
    {
        id: "planet-apes",
        title: "Hành Tinh Khỉ: Vương Quốc Mới",
        originalTitle: "Kingdom of the Planet of the Apes",
        genres: "Khoa học viễn tưởng, Hành động, Phiêu lưu",
        rating: "T13",
        score: 8.4,
        voteCount: "17.3K",
        duration: "145 phút",
        releaseDate: "10/05/2026",
        formats: ["IMAX 2D", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
        trailerUrl: "https://www.youtube.com/embed/Kdr5eedWD3w",
        isHot: false,
        isEarlyScreening: false,
        synopsis: "Nhiều thế hệ sau triều đại của Caesar, một thủ lĩnh vượn tàn bạo xây dựng đế chế của mình trong khi một chú vượn trẻ dấn thân vào hành trình định đoạt tương lai.",
    },
    {
        id: "barbie",
        title: "Barbie: Thế Giới Rực Rỡ",
        originalTitle: "Barbie",
        genres: "Hài hước, Giả tưởng, Phiêu lưu",
        rating: "T13",
        score: 8.9,
        voteCount: "43.9K",
        duration: "114 phút",
        releaseDate: "21/07/2026",
        formats: ["2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        trailerUrl: "https://www.youtube.com/embed/pBk4NYhWNMM",
        isHot: false,
        isEarlyScreening: false,
        synopsis: "Sống ở Barbieland hoàn hảo, Barbie bỗng trải qua cuộc khủng hoảng hiện sinh và phải dấn thân vào thế giới thực cùng Ken để tìm lại bản thân.",
    },
    {
        id: "avatar-way-of-water",
        title: "Avatar: Dòng Chảy Của Nước",
        originalTitle: "Avatar: The Way of Water",
        genres: "Khoa học viễn tưởng, Phiêu lưu, Hành động",
        rating: "T13",
        score: 9.4,
        voteCount: "82.5K",
        duration: "192 phút",
        releaseDate: "16/12/2026",
        formats: ["IMAX 2D", "3D", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        trailerUrl: "https://www.youtube.com/embed/d9MyW72ELq0",
        isHot: true,
        isEarlyScreening: false,
        synopsis: "Jake Sully và Neytiri cùng các con phải rời bỏ ngôi nhà rừng rậm để nương náu tại các rạn san hô biển của Pandora khi mối hiểm họa cũ quay trở lại.",
    }
];

export const GENRE_OPTIONS = [
    { value: "all", label: "Tất cả thể loại" },
    { value: "Hành động", label: "Hành động" },
    { value: "Khoa học viễn tưởng", label: "Khoa học viễn tưởng" },
    { value: "Hoạt hình", label: "Hoạt hình" },
    { value: "Hài hước", label: "Hài hước" },
    { value: "Phiêu lưu", label: "Phiêu lưu" },
    { value: "Gia đình", label: "Gia đình" },
    { value: "Kịch tính", label: "Kịch tính" },
];

export const FORMAT_OPTIONS = [
    { value: "all", label: "Tất cả định dạng" },
    { value: "IMAX 2D", label: "IMAX 2D" },
    { value: "2D Phụ đề", label: "2D Phụ đề" },
    { value: "2D Lồng tiếng", label: "2D Lồng tiếng" },
    { value: "3D", label: "3D" },
];

export const AGE_RATING_OPTIONS = [
    { value: "all", label: "Tất cả độ tuổi" },
    { value: "P", label: "P - Phổ biến (Mọi lứa tuổi)" },
    { value: "K", label: "K - Dưới 13 tuổi (Kèm PH)" },
    { value: "T13", label: "T13 - Khán giả từ 13 tuổi" },
    { value: "T16", label: "T16 - Khán giả từ 16 tuổi" },
    { value: "T18", label: "T18 - Khán giả từ 18 tuổi" },
];

export const SORT_OPTIONS = [
    { value: "score_desc", label: "Đánh giá cao nhất ⭐" },
    { value: "hot", label: "Độ phổ biến / Hot 🔥" },
    { value: "duration_desc", label: "Thời lượng dài nhất ⏳" },
    { value: "title_asc", label: "Tên phim (A - Z) 🔤" },
];
