// Verified & curated Coming Soon cinema data for CineMeow

export const COMMING_SOON_MOVIES = [
    {
        id: "gladiator-2",
        title: "Võ Sĩ Giác Đấu II",
        originalTitle: "Gladiator II",
        genres: "Hành động, Lịch sử, Phiêu lưu",
        rating: "T18",
        expectedScore: 9.3,
        wantToSeeCount: "42.8K",
        duration: "148 phút",
        releaseDate: "15/11/2026",
        releaseMonth: "2026-11",
        daysLeft: 12,
        formats: ["IMAX 2D", "4DX", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w780/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
        trailerUrl: "https://www.youtube.com/embed/4rgYUipGJNo",
        isHot: true,
        isPreSale: true,
        synopsis: "Tiếp nối thiên sử thi của đạo diễn Ridley Scott, Lucius bước vào Đấu trường La Mã khốc liệt để giành lại vinh quang và tự do cho đế chế Roma.",
    },
    {
        id: "moana-2",
        title: "Hành Trình Của Moana 2",
        originalTitle: "Moana 2",
        genres: "Hoạt hình, Âm nhạc, Phiêu lưu",
        rating: "P",
        expectedScore: 9.0,
        wantToSeeCount: "38.5K",
        duration: "100 phút",
        releaseDate: "27/11/2026",
        releaseMonth: "2026-11",
        daysLeft: 24,
        formats: ["2D Lồng tiếng", "2D Phụ đề", "3D"],
        poster: "https://image.tmdb.org/t/p/w780/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        trailerUrl: "https://www.youtube.com/embed/hDZ7y8RP5HE",
        isHot: true,
        isPreSale: true,
        synopsis: "Sau khi nhận được tiếng gọi bất ngờ từ tổ tiên dẫn đường, Moana bắt đầu cuộc hành trình vượt qua những vùng biển xa xôi nguy hiểm của Châu Đại Dương.",
    },
    {
        id: "wicked-part-1",
        title: "Wicked: Phù Thủy Xứ Oz",
        originalTitle: "Wicked: Part One",
        genres: "Kỳ ảo, Âm nhạc, Tình cảm",
        rating: "T13",
        expectedScore: 9.1,
        wantToSeeCount: "29.4K",
        duration: "160 phút",
        releaseDate: "22/11/2026",
        releaseMonth: "2026-11",
        daysLeft: 19,
        formats: ["IMAX 2D", "2D Phụ đề", "Dolby Atmos"],
        poster: "https://image.tmdb.org/t/p/w780/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        trailerUrl: "https://www.youtube.com/embed/6COmYeLsz4c",
        isHot: true,
        isPreSale: true,
        synopsis: "Câu chuyện chưa kể về tình bạn và định mệnh trớ trêu giữa Elphaba - Phù thủy xứ Tây và Glinda - Phù thủy phương Bắc trong thế giới Oz nhiệm màu.",
    },
    {
        id: "avatar-3",
        title: "Avatar 3: Lửa Và Tro Tàn",
        originalTitle: "Avatar: Fire and Ash",
        genres: "Khoa học viễn tưởng, Phiêu lưu, Hành động",
        rating: "T13",
        expectedScore: 9.6,
        wantToSeeCount: "68.2K",
        duration: "195 phút",
        releaseDate: "19/12/2026",
        releaseMonth: "2026-12",
        daysLeft: 46,
        formats: ["IMAX 3D", "3D HFR", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w780/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w",
        isHot: true,
        isPreSale: false,
        synopsis: "James Cameron mở rộng vũ trụ Pandora với tộc người Tro Tàn (Ash People) hiếu chiến cùng tộc biển Metkayina trong trận chiến sống còn bảo vệ hành tinh mẹ.",
    },
    {
        id: "mufasa-lion-king",
        title: "Mufasa: Vua Sư Tử",
        originalTitle: "Mufasa: The Lion King",
        genres: "Hoạt hình, Gia đình, Phiêu lưu",
        rating: "P",
        expectedScore: 8.9,
        wantToSeeCount: "31.7K",
        duration: "118 phút",
        releaseDate: "20/12/2026",
        releaseMonth: "2026-12",
        daysLeft: 47,
        formats: ["IMAX 2D", "2D Lồng tiếng", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w780/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
        trailerUrl: "https://www.youtube.com/embed/o17MF9vnabg",
        isHot: true,
        isPreSale: false,
        synopsis: "Khám phá câu chuyện tuổi trẻ của vị vua vĩ đại Mufasa từ một chú sư tử mồ côi cô độc đến khi trở thành lãnh chúa uy quyền của Vùng Đất Kiêu Hãnh.",
    },
    {
        id: "sonic-3",
        title: "Nhím Sonic 3",
        originalTitle: "Sonic the Hedgehog 3",
        genres: "Hành động, Hài hước, Gia đình",
        rating: "K",
        expectedScore: 8.8,
        wantToSeeCount: "25.1K",
        duration: "110 phút",
        releaseDate: "25/12/2026",
        releaseMonth: "2026-12",
        daysLeft: 52,
        formats: ["2D Lồng tiếng", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        trailerUrl: "https://www.youtube.com/embed/qSu6i2iFMO0",
        isHot: false,
        isPreSale: false,
        synopsis: "Sonic, Knuckles và Tails đối đầu với đối thủ nguy hiểm bậc nhất: Shadow the Hedgehog - một thực thể bí ẩn sở hữu sức mạnh vượt trội.",
    },
    {
        id: "captain-america-brave-new-world",
        title: "Captain America: Thế Giới Mới Dũng Cảm",
        originalTitle: "Captain America: Brave New World",
        genres: "Hành động, Siêu anh hùng, Khoa học viễn tưởng",
        rating: "T13",
        expectedScore: 9.0,
        wantToSeeCount: "51.4K",
        duration: "135 phút",
        releaseDate: "14/02/2027",
        releaseMonth: "2027-02",
        daysLeft: 103,
        formats: ["IMAX 2D", "4DX", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w780/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
        trailerUrl: "https://www.youtube.com/embed/1pHDWnXmKMY",
        isHot: true,
        isPreSale: false,
        synopsis: "Sam Wilson chính thức gánh vác chiếc khiên Captain America, bước vào vòng xoáy âm mưu chính trị toàn cầu và đối đầu với Red Hulk khổng lồ.",
    },
    {
        id: "fantastic-four-first-steps",
        title: "Bộ Tứ Siêu Đẳng: First Steps",
        originalTitle: "The Fantastic Four: First Steps",
        genres: "Khoa học viễn tưởng, Hành động, Phiêu lưu",
        rating: "T13",
        expectedScore: 9.1,
        wantToSeeCount: "44.9K",
        duration: "130 phút",
        releaseDate: "25/07/2027",
        releaseMonth: "2027-07",
        daysLeft: 265,
        formats: ["IMAX 2D", "3D", "2D Phụ đề"],
        poster: "https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        trailerUrl: "https://www.youtube.com/embed/18QQWa3Wcx0",
        isHot: true,
        isPreSale: false,
        synopsis: "Gia đình siêu anh hùng đầu tiên của Marvel bước vào MCU trong bối cảnh retro-future thập niên 1960 chống lại kẻ nuốt chửng thế giới Galactus.",
    },
    {
        id: "conan-movie-28",
        title: "Thám Tử Lừng Danh Conan: Movie 28",
        originalTitle: "Detective Conan Movie 28",
        genres: "Hoạt hình, Trinh thám, Hành động",
        rating: "P",
        expectedScore: 9.4,
        wantToSeeCount: "36.2K",
        duration: "112 phút",
        releaseDate: "25/04/2027",
        releaseMonth: "2027-04",
        daysLeft: 173,
        formats: ["2D Lồng tiếng", "2D Phụ đề", "IMAX 2D"],
        poster: "https://image.tmdb.org/t/p/w780/unthV1mq9llhEinIMPcCUImFodt.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/unthV1mq9llhEinIMPcCUImFodt.jpg",
        trailerUrl: "https://www.youtube.com/embed/K84CjJ6Z6rI",
        isHot: true,
        isPreSale: false,
        synopsis: "Phần phim điện ảnh thứ 28 của thương hiệu Conan hé lộ vụ án bí ẩn tại Nagano cùng sự tái xuất của Sở cảnh sát Tokyo và Tổ chức Áo Đen.",
    }
];

export const MONTH_OPTIONS = [
    { value: "all", label: "Tất cả các tháng" },
    { value: "2026-11", label: "Tháng 11 / 2026" },
    { value: "2026-12", label: "Tháng 12 / 2026" },
    { value: "2027-02", label: "Tháng 02 / 2027" },
    { value: "2027-04", label: "Tháng 04 / 2027" },
    { value: "2027-07", label: "Tháng 07 / 2027" },
];

export const GENRE_OPTIONS = [
    { value: "all", label: "Tất cả thể loại" },
    { value: "Hành động", label: "Hành động" },
    { value: "Khoa học viễn tưởng", label: "Khoa học viễn tưởng" },
    { value: "Hoạt hình", label: "Hoạt hình" },
    { value: "Phiêu lưu", label: "Phiêu lưu" },
    { value: "Gia đình", label: "Gia đình" },
    { value: "Kỳ ảo", label: "Kỳ ảo" },
    { value: "Âm nhạc", label: "Âm nhạc" },
];

export const AGE_RATING_OPTIONS = [
    { value: "all", label: "Tất cả độ tuổi", rating: null },
    { value: "P", label: "P - Mọi lứa tuổi", shortLabel: "P", rating: "P" },
    { value: "K", label: "K - Dưới 13 tuổi có giám hộ", shortLabel: "K", rating: "K" },
    { value: "T13", label: "T13 - Khán giả từ 13+", shortLabel: "T13", rating: "T13" },
    { value: "T16", label: "T16 - Khán giả từ 16+", shortLabel: "T16", rating: "T16" },
    { value: "T18", label: "T18 - Khán giả từ 18+", shortLabel: "T18", rating: "T18" },
];

export const SORT_OPTIONS = [
    { value: "release_asc", label: "Ngày khởi chiếu sớm nhất" },
    { value: "want_desc", label: "Lượng người mong đợi cao nhất" },
    { value: "score_desc", label: "Điểm kỳ vọng cao nhất" },
    { value: "title_asc", label: "Tên phim (A - Z)" },
];
